### ISSUE TITLE
请问如何运行这个java程序

### ISSUE THREAD

**Issue by cf3i** [lerry-lee/faq-qa-sys#1]
作为一个常年使用C++的蒟蒻，最近对java感兴趣，想运行一下您的faq system。但无奈不熟悉java，不知道如何启动。

**Comment by lerry-lee** [comment]
@B4night 按照readme的步骤就可以了，如果对Java不熟悉可以先去简单了解下Java和SpringBoot哦

**Comment by lerry-lee** [comment]
@B4night 比较简单的方式你下载个IEDA，然后打开该项目，直接run启动类`src/main/java/com/example/qa/QuestionAnsweringSystemApplication.java`也行，当然要先确认配置文件连接的数据库等都是正常的
